spring:
  application:
    name: spring-ai-hands-on
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  ai:
    mistralai:
      embedding:
        api-key: ${MISTRAL_AI_API_KEY}
      chat:
        api-key: ${MISTRAL_AI_API_KEY}
    openai:
      api-key: ${OPEN_API_API_KEY}
    vectorstore:
      pgvector:
        dimensions: 1024
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8083
  servlet:
    context-path: /api
